# Generated by Django 3.2.5 on 2021-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0003_log_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_in',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='log_in',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='first_name',
            field=models.CharField(blank=True, default='USER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
