# Generated by Django 3.2.5 on 2021-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0005_auto_20210715_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='emails',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='log_in',
            old_name='passwords',
            new_name='username',
        ),
    ]
