# Generated by Django 3.2.5 on 2021-07-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0006_auto_20210715_1529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sign_up',
            table='b',
        ),
    ]
