# Generated by Django 3.2.5 on 2021-07-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0007_alter_sign_up_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='bo',
        ),
        migrations.AlterModelTable(
            name='sign_up',
            table=None,
        ),
    ]
