# Generated by Django 3.2.5 on 2021-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0008_auto_20210720_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('avalible', 'avalible'), ('rental', 'rental'), ('Notavalible', 'Notavalible')], max_length=50, null=True),
        ),
    ]
