# Generated by Django 3.2.5 on 2021-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0009_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('Not_avalible', 'Not_avalible')], max_length=50, null=True),
        ),
    ]
