# Generated by Django 3.2.5 on 2021-07-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbook', '0011_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('Not_avalible', 'Not_avalible')], default='available', max_length=50, null=True),
        ),
    ]
